---
- name: "Download local copy of fixpack installer"
  get_url:
    url: "{{ download_FP_url }}{{ item }}"
    dest: "{{ Extract_FP_location }}"
  with_items:
    - 8.5.5-WS-WAS-FP013-part1.zip
    - 8.5.5-WS-WAS-FP013-part2.zip
    - 8.5.5-WS-WAS-FP013-part3.zip

- name: "Extract fixpack archive"
  unarchive:
    src: "{{ Extract_FP_location }}{{ item }}"
    dest: "{{ Extract_FP_location }}"
    copy: no
  with_items:
    - 8.5.5-WS-WAS-FP013-part1.zip
    - 8.5.5-WS-WAS-FP013-part2.zip
    - 8.5.5-WS-WAS-FP013-part3.zip

- name: "Run slient install on {{installationDirectory}}"
  command: '{{imcl_path}} install com.ibm.websphere.BASE.v85_8.5.5012.20170627_1018 -repositories "{{ Extract_FP_location }}" -installationDirectory "{{ installationDirectory }}" -acceptLicense -sP'

- name: "Remove fixPacks packages"
  file: "path=\"{{Extract_FP_location}}{{item}}\" state=absent"
  with_items:
    - 8.5.5-WS-WAS-FP013-part1.zip
    - 8.5.5-WS-WAS-FP013-part2.zip
    - 8.5.5-WS-WAS-FP013-part3.zip

- name: "Clean up the unarchived FP Dir"
  file: "path=\"{{Extract_FP_location}}\" state=absent"
