---
- name: "Download local copy of was installer."
  get_url:
    url: "{{ download_WAS_url }}{{ item }}"
    dest: "{{Extract_WAS_location}}"
  with_items:
    - "{{ WAS9 }}"

- name: "Extract was8 archive"
  unarchive: 
  unarchive: 
    dest: "{{ Extract_WAS_location }}"
    src: "{{ Extract_WAS_location }}{{ item }}"
    copy: no
  with_items: 
    - "{{ WAS9 }}"

- name: "Run slient install into {{installationDirectory}}"
<<<<<<< HEAD
  command: '{{imcl_path}} install com.ibm.websphere.BASE.v90_9.0.9.20180906_1004 -repositories {{ Extract_WAS_location }} -installationDirectory  {{installationDirectory}} -acceptLicense -sP'
  args:                            
=======
  command: '{{imcl_path}} install com.ibm.websphere.BASE.v85_8.5.5013.20180112_1418 -repositories {{ Extract_WAS_location }} -installationDirectory  {{installationDirectory}} -acceptLicense -sP'
  args: 
>>>>>>> 93b103f29578fd95cf8910735f602362755b356e
    creates: /opt/tools/IBM/WebSphere/AppServer/bin/versionInfo.sh
  
- name: "Remove was8 packages"
  file: "path=\"{{Extract_WAS_location}}{{item}}\" state=absent"
  with_items: 
    - "{{ WAS9 }}"
- name: "Clean up the unarchived WAS Dir"
  file: "path=\"{{Extract_WAS_location}}\" state=absent"
